name: lotura_v2
description: "Lotura is for you ðŸ˜˜"

publish_to: 'none'

# ë¬¸ì˜í•˜ê¸° ì—°ê²° ë§í¬ ìˆ˜ì •
version: 2.6.2+14

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.2.3
  flutter_svg: ^2.0.10+1
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.3.0
  web_socket_channel: ^3.0.1
  dio: ^5.7.0
  flutter_markdown: ^0.7.4
#  firebase_messaging: ^15.1.3
#  flutter_local_notifications: ^17.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.12
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/icon/core/lotura_app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/icon/core/
    - assets/icon/laundry/
    - assets/icon/notice/
    - assets/icon/setting/
    - assets/icon/theme/
    - assets/icon/theme/bell/
    - assets/image/core/
    - assets/image/apply/
    - assets/image/notice/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard_semibold.otf
          weight: 600
        - asset: assets/fonts/pretendard_medium.otf
          weight: 500
        - asset: assets/fonts/pretendard_regular.otf
          weight: 400
